### ISSUE TITLE
Client side Validation

### ISSUE THREAD

**Issue by natrenakres** [Veams/veams-component-form#3]
Hi,

I try to validate the form before submit. Is there any function for client side validation? Or how can I get validation state of form before submit it?

Best Regards
Serkan

**Comment by koenz** [comment]
Hi Serkan,

You can use native browser validation and customise it in from-ajax.js. The component doesn't ship with client-side validation. 

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

**Comment by natrenakres** [comment]
Hi @koenz thanks for answer.
